name: All Platforms Build 

on:
  push:
    branches: [main] 
  pull_request:
    branches: [main] 

jobs:
  build-linux:
    name: Build on Ubuntu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build project
        run: cmake --build build

      - name: Package with CPack
        run: |
          cd build
          cpack

      - name: Upload Artifact (TGZ)
        uses: actions/upload-artifact@v3
        with:
          name: solver-linux
          path: build/*.tar.gz

  build-windows:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build project
        run: cmake --build build --config Release

      - name: Package with CPack
        run: |
          cd build
          cpack

      - name: Upload Artifact (ZIP)
        uses: actions/upload-artifact@v3
        with:
          name: solver-windows
          path: build/*.zip

  build-macos:
    name: Build on macOS
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build project
        run: cmake --build build

      - name: Package with CPack
        run: |
          cd build
          cpack

      - name: Upload Artifact (ZIP)
        uses: actions/upload-artifact@v3
        with:
          name: solver-macos
          path: build/*.zip
